import Head from "next/head";
import { Container } from "@chakra-ui/react";
import axios from "axios";
import { useState, useEffect } from "react";

export default function Home() {
  const [cards, setCards] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");

  useEffect(() => {
    axios
      .get("https://api.scryfall.com/cards/search?order=cmc&q=c%3Ared+pow%3D3")
      .then((response) => {
        setCards(response.data.data);
        console.log(cards);
      });
  }, [searchTerm]);

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <input
            type="text"
            onChange={(e) => setSearchTerm(e.target.value)}
          ></input>
        </div>
        {cards.map((card) => {
          return card.card_faces ? (
            <img src={card.card_faces[0].image_uris?.png} />
          ) : (
            <>
              <img src={card.image_uris?.png} />
            </>
          );
        })}
      </main>

      <footer></footer>
    </Container>
  );
}
